USE ODW;

CREATE TABLE ODW_BOARD (
	NUM 		INT PRIMARY KEY AUTO_INCREMENT,
    WRITER		VARCHAR(20),
    TITLE		VARCHAR(50),
    REG_DATE	DATE,
    READ_COUNT	INT,
    CONTENT		VARCHAR(1000),
    IMAGE		VARCHAR(100),
    FOREIGN KEY(WRITER) REFERENCES ODW_MEMBER(MEMBER_ID) ON DELETE CASCADE
);

SELECT
		*
FROM
		ODW_BOARD;
        
DROP TABLE ODW_BOARD;

