USE ODW;

CREATE TABLE ODW_LIKE (
	LIKE_SEND		VARCHAR(20),
    LIKE_RECEIVE	VARCHAR(20),
    FOREIGN KEY(LIKE_SEND) REFERENCES ODW_MEMBER(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(LIKE_RECEIVE) REFERENCES ODW_MEMBER(MEMBER_ID) ON DELETE CASCADE
);

SELECT
		*
FROM
		ODW_LIKE;
        
DROP TABLE ODW_LIKE;


