USE ODW;

CREATE TABLE ODW_REPLY (
	NUM 		INT PRIMARY KEY AUTO_INCREMENT,
    B_NUM		INT,
    WRITER		VARCHAR(20),
    CONTENT		VARCHAR(1000),
    REG_DATE	DATE,
    FOREIGN KEY(WRITER) REFERENCES ODW_MEMBER(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(B_NUM) REFERENCES ODW_BOARD(NUM) ON DELETE CASCADE
);

SELECT
		*
FROM
		ODW_REPLY;
        
DROP TABLE ODW_REPLY;
